version: 3.3
services: 
  app:
    build:
      context: .
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_URLS: 'localhost:5000'
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    hostname: "redis"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "read_model"
      POSTGRES_USER: "read_model_owner"
      POSTGRES_PASSWORD: "qwerty"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    ports:
      - '9200:9200'